ENTITY_CONFIGS = [
    {
        "key": "sucursales",
        "title": "Sucursales",
        "singular_title": "Sucursal",
        "tagline": "Alta y administracion de sucursales para cuentas ADMIN.",
        "endpoint": "/apiManGen/Sucursal",
        "id_field": "id",
        "icon": "STOREFRONT",
        "admin_only": True,
        "fields": [
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
        ],
        "table_columns": ["nombre"],
        "summary_fields": ["nombre"],
        "filters": [
            {"key": "nombre", "label": "Buscar sucursal", "type": "text"},
        ],
        "extra_actions": ["backfill"],
    },
    {
        "key": "usuarios",
        "title": "Usuarios",
        "singular_title": "Usuario",
        "tagline": "Gestion de accesos y roles por sucursal.",
        "endpoint": "/apiManGen/User",
        "id_field": "id",
        "icon": "GROUPS",
        "admin_only": True,
        "fields": [
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
            {
                "key": "fechaCreacion",
                "label": "Fecha de creacion",
                "type": "date",
                "required": True,
                "include_time": True,
                "auto_now_local_on_create": True,
            },
            {"key": "email", "label": "Email", "type": "text", "required": True},
            {"key": "password", "label": "Contrasena", "type": "password", "required": True, "create_only": True},
            {"key": "password", "label": "Nueva contrasena", "type": "password", "required": False, "edit_only": True},
            {
                "key": "roll",
                "label": "Rol",
                "type": "select",
                "required": True,
                "options": ["ADMIN", "USER"],
            },
        ],
        "table_columns": ["nombre", "email", "roll", "fechaCreacion"],
        "summary_fields": ["nombre", "email", "roll", "fechaCreacion"],
        "filters": [
            {"key": "nombre", "label": "Nombre", "type": "text"},
            {"key": "email", "label": "Email", "type": "text"},
            {"key": "roll", "label": "Rol", "type": "select", "options": ["ADMIN", "USER"]},
            {"key": "fechaCreacion", "label": "Fecha de creacion", "type": "date"},
        ],
    },
    {
        "key": "materias_primas",
        "title": "Materias Primas",
        "singular_title": "Materia Prima",
        "tagline": "Stock base para produccion y costos.",
        "endpoint": "/apiManGen/Materia_prima",
        "id_field": "id",
        "icon": "SCIENCE",
        "fields": [
            {"key": "asset", "label": "Asset", "type": "text", "required": False},
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
            {"key": "precio", "label": "Precio", "type": "number", "required": True},
            {
                "key": "unidad",
                "label": "Unidad",
                "type": "select",
                "required": True,
                "options": ["unidad", "litro", "kilogramo"],
            },
            {"key": "cantidad", "label": "Cantidad", "type": "number", "required": True},
        ],
        "table_columns": ["nombre", "precio", "unidad", "cantidad", "asset"],
        "summary_fields": ["nombre", "precio", "unidad", "cantidad"],
        "filters": [
            {"key": "nombre", "label": "Nombre", "type": "text"},
            {"key": "unidad", "label": "Unidad", "type": "select", "options": ["unidad", "litro", "kilogramo"]},
        ],
    },
    {
        "key": "productos",
        "title": "Productos",
        "singular_title": "Producto",
        "tagline": "Catalogo de venta con relacion de materias primas.",
        "endpoint": "/apiManGen/Producto",
        "id_field": "id",
        "icon": "INVENTORY_2",
        "fields": [
            {"key": "asset", "label": "Asset", "type": "text", "required": False},
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
            {"key": "precio", "label": "Precio", "type": "number", "required": True},
            {"key": "cantidad", "label": "Cantidad", "type": "number", "required": True},
            {
                "key": "unidad",
                "label": "Unidad",
                "type": "select",
                "required": True,
                "options": ["unidad", "litro", "kilogramo"],
            },
        ],
        "table_columns": ["nombre", "precio", "cantidad", "unidad", "asset"],
        "summary_fields": ["nombre", "precio", "cantidad", "unidad"],
        "filters": [
            {"key": "nombre", "label": "Nombre", "type": "text"},
            {"key": "unidad", "label": "Unidad", "type": "select", "options": ["unidad", "litro", "kilogramo"]},
        ],
        "relation": {
            "title": "Materias primas asociadas",
            "list_path": "/apiManGen/Producto/{id}/materias-primas",
            "create_path": "/apiManGen/Producto/{id}/materias-primas",
            "update_path": "/apiManGen/Producto/{id}/materias-primas/{related_id}/cantidad",
            "related_endpoint": "/apiManGen/Materia_prima",
            "payload_id_key": "materiaPrimaId",
            "empty_text": "Este producto todavia no tiene materias primas asociadas.",
        },
    },
    {
        "key": "pedidos",
        "title": "Pedidos",
        "singular_title": "Pedido",
        "tagline": "Pedidos comerciales sin impacto automatico en stock.",
        "endpoint": "/apiManGen/Pedidos",
        "id_field": "id",
        "icon": "RECEIPT_LONG",
        "fields": [
            {"key": "total", "label": "Total", "type": "number", "required": True},
            {"key": "totalDesc", "label": "Total con descuento", "type": "number", "required": True},
            {"key": "descripcion", "label": "Descripcion", "type": "text", "required": False, "multiline": True},
            {
                "key": "estado",
                "label": "Estado",
                "type": "select",
                "required": True,
                "options": ["Pendiente", "Preparado", "Listo"],
            },
        ],
        "table_columns": ["total", "totalDesc", "descripcion", "estado"],
        "summary_fields": ["estado", "total", "totalDesc", "descripcion"],
        "filters": [
            {"key": "descripcion", "label": "Descripcion", "type": "text"},
            {"key": "estado", "label": "Estado", "type": "select", "options": ["Pendiente", "Preparado", "Listo"]},
        ],
        "relation": {
            "title": "Productos del pedido",
            "list_path": "/apiManGen/Pedidos/{id}/productos",
            "create_path": "/apiManGen/Pedidos/{id}/productos",
            "update_path": "/apiManGen/Pedidos/{id}/productos/{related_id}/cantidad",
            "related_endpoint": "/apiManGen/Producto",
            "payload_id_key": "productoId",
            "empty_text": "Este pedido todavia no tiene productos asociados.",
            "related_label_key": "nombre",
            "price_field": "precio",
        },
    },
    {
        "key": "ventas",
        "title": "Ventas",
        "singular_title": "Venta",
        "tagline": "Ventas manuales o desde pedido, con o sin impacto en stock.",
        "endpoint": "/apiManGen/Ventas",
        "id_field": "id",
        "icon": "POINT_OF_SALE",
        "fields": [
            {"key": "total", "label": "Total", "type": "number", "required": True},
            {"key": "totalDesc", "label": "Total con descuento", "type": "number", "required": True},
            {"key": "metodoPago", "label": "Metodo de pago", "type": "text", "required": True},
            {"key": "fecha", "label": "Fecha", "type": "date", "required": False},
        ],
        "table_columns": ["total", "totalDesc", "metodoPago", "fecha"],
        "summary_fields": ["metodoPago", "total", "totalDesc", "fecha"],
        "filters": [
            {"key": "metodoPago", "label": "Metodo de pago", "type": "text"},
            {"key": "fecha", "label": "Fecha", "type": "date"},
        ],
        "relation": {
            "title": "Productos de la venta",
            "list_path": "/apiManGen/Ventas/{id}/productos",
            "create_path": "/apiManGen/Ventas/{id}/productos",
            "create_path_stock": "/apiManGen/Ventas/{id}/productos/con-stock",
            "update_path": "/apiManGen/Ventas/{id}/productos/{related_id}/cantidad",
            "update_path_stock": "/apiManGen/Ventas/{id}/productos/{related_id}/cantidad/con-stock",
            "delete_path": "/apiManGen/Ventas/{id}/productos/{related_id}",
            "delete_path_stock": "/apiManGen/Ventas/{id}/productos/{related_id}/con-stock",
            "related_endpoint": "/apiManGen/Producto",
            "payload_id_key": "productoId",
            "empty_text": "Esta venta todavia no tiene productos asociados.",
            "related_label_key": "nombre",
            "price_field": "precio",
        },
        "extra_actions": ["from_pedido"],
    },
]
