ENTITY_CONFIGS = [
    {
        "key": "sucursales",
        "title": "Sucursales",
        "singular_title": "Sucursal",
        "endpoint": "/apiManGen/Sucursal",
        "id_field": "id",
        "admin_only": True,
        "fields": [
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
        ],
        "table_columns": ["nombre"],
        "extra_actions": ["backfill"],
    },
    {
        "key": "usuarios",
        "title": "Usuarios",
        "singular_title": "Usuario",
        "endpoint": "/apiManGen/User",
        "id_field": "id",
        "admin_only": True,
        "fields": [
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
            {
                "key": "fechaCreacion",
                "label": "Fecha de creacion",
                "type": "date",
                "required": True,
                "include_time": True,
                "auto_now_local_on_create": True,
            },
            {"key": "email", "label": "Email", "type": "text", "required": True},
            {"key": "password", "label": "Contrasena", "type": "password", "required": True, "create_only": True},
            {"key": "password", "label": "Nueva contrasena", "type": "password", "required": False, "edit_only": True},
            {
                "key": "roll",
                "label": "Rol",
                "type": "select",
                "required": True,
                "options": ["ADMIN", "USER"],
            },
        ],
        "table_columns": ["nombre", "email", "roll", "fechaCreacion"],
    },
    {
        "key": "materias_primas",
        "title": "Materias Primas",
        "singular_title": "Materia Prima",
        "endpoint": "/apiManGen/Materia_prima",
        "id_field": "id",
        "fields": [
            {"key": "asset", "label": "Asset", "type": "text", "required": False},
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
            {"key": "precio", "label": "Precio", "type": "number", "required": True},
            {
                "key": "unidad",
                "label": "Unidad",
                "type": "select",
                "required": True,
                "options": ["unidad", "litro", "kilogramo"],
            },
            {"key": "cantidad", "label": "Cantidad", "type": "number", "required": True},
        ],
        "table_columns": ["nombre", "precio", "unidad", "cantidad", "asset"],
    },
    {
        "key": "productos",
        "title": "Productos",
        "singular_title": "Producto",
        "endpoint": "/apiManGen/Producto",
        "id_field": "id",
        "fields": [
            {"key": "asset", "label": "Asset", "type": "text", "required": False},
            {"key": "nombre", "label": "Nombre", "type": "text", "required": True},
            {"key": "precio", "label": "Precio", "type": "number", "required": True},
            {"key": "cantidad", "label": "Cantidad", "type": "number", "required": True},
            {
                "key": "unidad",
                "label": "Unidad",
                "type": "select",
                "required": True,
                "options": ["unidad", "litro", "kilogramo"],
            },
        ],
        "table_columns": ["nombre", "precio", "cantidad", "unidad", "asset"],
        "relation": {
            "title": "Materias primas asociadas",
            "list_path": "/apiManGen/Producto/{id}/materias-primas",
            "create_path": "/apiManGen/Producto/{id}/materias-primas",
            "update_path": "/apiManGen/Producto/{id}/materias-primas/{related_id}/cantidad",
            "related_endpoint": "/apiManGen/Materia_prima",
            "payload_id_key": "materiaPrimaId",
        },
    },
    {
        "key": "pedidos",
        "title": "Pedidos",
        "singular_title": "Pedido",
        "endpoint": "/apiManGen/Pedidos",
        "id_field": "id",
        "fields": [
            {"key": "total", "label": "Total", "type": "number", "required": True},
            {"key": "totalDesc", "label": "Total con descuento", "type": "number", "required": True},
            {"key": "descripcion", "label": "Descripcion", "type": "text", "required": False, "multiline": True},
            {"key": "estado", "label": "Estado", "type": "text", "required": True},
        ],
        "table_columns": ["total", "totalDesc", "descripcion", "estado"],
        "relation": {
            "title": "Productos del pedido",
            "list_path": "/apiManGen/Pedidos/{id}/productos",
            "create_path": "/apiManGen/Pedidos/{id}/productos",
            "update_path": "/apiManGen/Pedidos/{id}/productos/{related_id}/cantidad",
            "related_endpoint": "/apiManGen/Producto",
            "payload_id_key": "productoId",
        },
    },
    {
        "key": "ventas",
        "title": "Ventas",
        "singular_title": "Venta",
        "endpoint": "/apiManGen/Ventas",
        "id_field": "id",
        "fields": [
            {"key": "total", "label": "Total", "type": "number", "required": True},
            {"key": "totalDesc", "label": "Total con descuento", "type": "number", "required": True},
            {"key": "metodoPago", "label": "Metodo de pago", "type": "text", "required": True},
            {"key": "fecha", "label": "Fecha", "type": "date", "required": False},
        ],
        "table_columns": ["total", "totalDesc", "metodoPago", "fecha"],
        "relation": {
            "title": "Productos de la venta",
            "list_path": "/apiManGen/Ventas/{id}/productos",
            "create_path": "/apiManGen/Ventas/{id}/productos",
            "create_path_stock": "/apiManGen/Ventas/{id}/productos/con-stock",
            "update_path": "/apiManGen/Ventas/{id}/productos/{related_id}/cantidad",
            "update_path_stock": "/apiManGen/Ventas/{id}/productos/{related_id}/cantidad/con-stock",
            "delete_path": "/apiManGen/Ventas/{id}/productos/{related_id}",
            "delete_path_stock": "/apiManGen/Ventas/{id}/productos/{related_id}/con-stock",
            "related_endpoint": "/apiManGen/Producto",
            "payload_id_key": "productoId",
        },
        "extra_actions": ["from_pedido", "from_pedido_stock"],
    },
]
